// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output mode for the task.
 *
 * - `full`: Displays all output
 * - `hash-only`: Show only the hashes of the tasks
 * - `new-only`: Only show output from cache misses
 * - `errors-only`: Only show output from task failures
 * - `none`: Hides all task output
 *
 * Documentation: https://turborepo.dev/docs/reference/run#--output-logs-option
 */
export type OutputLogs =
  | "full"
  | "none"
  | "hash-only"
  | "new-only"
  | "errors-only";
