// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enable use of the UI for `turbo`.
 *
 * Documentation: https://turborepo.dev/docs/reference/configuration#ui
 */
export type UI = "tui" | "stream";
