/**
 * Reads template files from src/templates/ and generates src/templates/embedded.ts
 * with their contents as string constants. This keeps a single source of truth
 * for templates while allowing them to be embedded in the compiled binary.
 *
 * Run: bun run scripts/embed-templates.ts
 */

import fs from "node:fs";
import path from "node:path";

const TEMPLATES_DIR = path.join(import.meta.dir, "..", "src", "templates");
const OUTPUT_FILE = path.join(TEMPLATES_DIR, "embedded.ts");

interface TemplateFile {
  relativePath: string;
  content: string;
}

interface TemplateSet {
  name: string;
  files: Array<TemplateFile>;
}

function collectFiles(dir: string, base: string = ""): Array<TemplateFile> {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: Array<TemplateFile> = [];

  for (const entry of entries) {
    const relativePath = base ? `${base}/${entry.name}` : entry.name;
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...collectFiles(fullPath, relativePath));
    } else {
      files.push({
        relativePath,
        content: fs.readFileSync(fullPath, "utf-8")
      });
    }
  }

  return files;
}

function escapeForTemplate(content: string): string {
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");
}

function generate(): void {
  const templateDirs = fs
    .readdirSync(TEMPLATES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory());

  const templates: Array<TemplateSet> = [];

  for (const dir of templateDirs) {
    const files = collectFiles(path.join(TEMPLATES_DIR, dir.name));
    templates.push({ name: dir.name, files });
  }

  const lines: Array<string> = [
    "// Auto-generated by scripts/embed-templates.ts -- do not edit manually.",
    "",
    "export interface EmbeddedFile {",
    "  relativePath: string;",
    "  content: string;",
    "}",
    "",
    "export interface EmbeddedTemplate {",
    "  files: Array<EmbeddedFile>;",
    "}",
    "",
    "export const TEMPLATES: Record<string, EmbeddedTemplate> = {"
  ];

  for (const template of templates) {
    lines.push(`  "${template.name}": {`);
    lines.push("    files: [");
    for (const file of template.files) {
      lines.push("      {");
      lines.push(`        relativePath: "${file.relativePath}",`);
      lines.push(`        content: \`${escapeForTemplate(file.content)}\``);
      lines.push("      },");
    }
    lines.push("    ]");
    lines.push("  },");
  }

  lines.push("};");
  lines.push("");

  fs.writeFileSync(OUTPUT_FILE, lines.join("\n"));
  console.log(`Generated ${OUTPUT_FILE} with ${templates.length} template(s)`);
}

generate();
