# Keep in sync with .editorconfig
max_width = 100

tab_spaces = 4
hard_tabs = false

format_strings = true
wrap_comments = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# do not apply 2024 edition formatting
style_edition = "2021"
