# golang parameters
ARG GO_VERSION

FROM troian/golang-cross:v${GO_VERSION}-base

# Install deps
RUN \
    set -x; \
    echo "Starting image build for Debian Stretch" \
 && apt-get update \
 && apt-get install --no-install-recommends -y -q \
        gcc \
        g++ \
 && apt -y autoremove \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
