packages:
  - "docs"
  - "cli"
  - "packages/*"
  - "benchmark"
  # Intentionally exclude the `npm` `turbo` package from the workspaces.
  - "!packages/turbo"
  - "!examples/*"
  - "packages/turbo-tracing-next-plugin/test/with-mongodb-mongoose"
  - "crates/next-dev/tests"
  - "crates/*/js"
