packages:
  - apps/*
  - cli
  - docs/*
  - packages/*
  - "!packages/turbo"
  - examples
  - "!examples/non-monorepo"
  - lockfile-tests

minimumReleaseAge: 2880

# We dogfood our own canaries, which are always younger than minimumReleaseAge.
minimumReleaseAgeExclude:
  - turbo
  - "@turbo/*"

onlyBuiltDependencies:
  - "@swc/core"
  - "@vercel/speed-insights"
  - core-js-pure
  - esbuild
  - sharp
