project_name: turbo
before:
  hooks:
    - make compile-protos
    - go mod tidy
builds:
  - id: turbo
    main: ./cmd/turbo
    binary: bin/turbo
    hooks:
      pre:
        - cmd: ./scripts/npm-native-packages/npm-native-packages.js {{ .Os }} {{ .Arch }} {{ .Version }}
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    targets:
      - android_arm64
      - freebsd_amd64
      - freebsd_arm64
      - linux_386
      - linux_arm
      - linux_mips64le
      - linux_ppc64le
      - windows_386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
archives:
  - id: github
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    wrap_in_directory: true
    replacements:
      amd64: 64
      386: 32
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
  - id: npm
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    wrap_in_directory: true
    replacements:
      amd64: 64
      386: 32
    format: tar.gz
    files:
      - LICENSE
      - src: 'scripts/npm-native-packages/build/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}/package.json'
        dst: 'workaround/..'
        strip_parent: true
      - src: 'scripts/npm-native-packages/build/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}/README.md'
        dst: 'workaround/..'
        strip_parent: true
      - src: 'scripts/npm-native-packages/build/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}/bin/*'
        dst: 'bin/'
        strip_parent: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: vercel
    name: turborepo
  ids:
    - github
  prerelease: auto
  disable: true
publishers:
  - name: npm
    ids:
     - npm
    cmd: 'npm publish{{ if .Prerelease }} --tag canary{{ end }} {{ abs .ArtifactPath }}'
