name: Turborepo Bug Report
description: Create a bug report for the Turborepo team
title: "[turborepo] "
labels: ["kind: bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: If you leave out sections there is a high likelihood it will be moved to the GitHub Discussions "Help" section.
  - type: input
    attributes:
      label: What version of Turborepo are you using?
      description: "For example: 1.0.0"
    validations:
      required: true
  - type: dropdown
    id: packageManager
    attributes:
      multiple: true
      label: What package manager are you using / does the bug impact?
      options:
        - npm
        - pnpm
        - Yarn v1
        - Yarn v2/v3 (node_modules linker only)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Mac
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior, please provide a clear code snippets that always reproduces the issue or a GitHub repository. Screenshots can be provided in the issue body below.
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction Repo
      description: Include a URL to a repository that reproduces this issue. This is optional, but increases the likelihood that we can help you!
    validations:
      required: false
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
  - type: markdown
    attributes:
      value: Contributors should be able to follow the steps provided in order to reproduce the bug.
  - type: markdown
    attributes:
      value: Thanks in advance!
