name: "Documentation update or improvement"
description: A request to update or improve documentation
title: "Docs: "
labels:
  - "template: documentation"
body:
  - type: markdown
    attributes:
      value: Before opening this issue to request a docs improvement, is this something you can help us with? Your contributions are welcomed and appreciated.
  - type: markdown
    attributes:
      value: Thank you for helping us improve the docs!
  - type: textarea
    attributes:
      label: What is the improvement or update you wish to see?
      description: "Example: I would like to see more examples of how to use `turbo run`. Or, the `turbo run` docs are missing information."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: "Example: https://turbo.build/repo/docs/reference/command-line-reference/run"
    validations:
      required: false
