blank_issues_enabled: false
contact_links:
  - name: Turbopack in Next.js Bug Report
    url: https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml
    about: Create a Next.js bug report for the Turbopack team
  - name: Ask for help
    url: https://github.com/vercel/turborepo/discussions/new?category=help
    about: Need to ask a question? Get help from the community.
  - name: Submit an idea
    url: https://github.com/vercel/turborepo/discussions/new?category=ideas
    about: Make feature requests and suggest improvements.
