[package]
name = "turborepo-query"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
axum = { workspace = true }
camino = "1.1.4"
itertools = { workspace = true }
miette = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
turbo-trace = { workspace = true }
turbopath = { workspace = true }
turborepo-errors = { workspace = true }
turborepo-lockfiles = { workspace = true }
turborepo-query-api = { workspace = true }
turborepo-repository = { path = "../turborepo-repository" }
turborepo-signals = { workspace = true }
turborepo-types = { workspace = true }
webbrowser = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
turborepo-engine = { workspace = true }
turborepo-microfrontends-config = { workspace = true }
turborepo-run-context = { workspace = true }
turborepo-scm = { workspace = true }
turborepo-task-id = { workspace = true }
turborepo-turbo-json = { workspace = true }
turborepo-ui = { workspace = true }

[lints]
workspace = true
