//! Streaming HTTP reverse proxy used by Portless.

use std::{
    collections::HashMap,
    convert::Infallible,
    error::Error as StdError,
    fmt::Write as _,
    future::Future,
    io::Cursor,
    net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr},
    path::PathBuf,
    sync::{Arc, Mutex, RwLock},
    time::Duration,
};

use bytes::Bytes;
use http_body_util::{BodyExt, Full, combinators::UnsyncBoxBody};
use hyper::{
    HeaderMap, Request, Response, StatusCode, Uri,
    body::Incoming,
    header::{CONTENT_TYPE, HOST},
    service::service_fn,
};
use hyper_util::{
    client::legacy::{Client, connect::HttpConnector},
    rt::{TokioExecutor, TokioIo},
};
use rustls::{
    ServerConfig,
    pki_types::{CertificateDer, PrivateKeyDer},
    server::{ClientHello, ResolvesServerCert},
    sign::CertifiedKey,
};
use tokio::{
    io::copy_bidirectional,
    net::{TcpListener, TcpSocket},
    sync::watch,
    task::JoinSet,
};
use tokio_rustls::TlsAcceptor;

use crate::pages::{ARROW_SVG, render_page};

/// Response header used by health checks to identify Portless.
pub const PORTLESS_HEADER: &str = "X-Portless";
const PORTLESS_HOPS_HEADER: &str = "x-portless-hops";
const MAX_PROXY_HOPS: u8 = 5;
const HOP_BY_HOP_HEADERS: [&str; 5] = [
    "connection",
    "keep-alive",
    "proxy-connection",
    "transfer-encoding",
    "upgrade",
];

type BoxError = Box<dyn StdError + Send + Sync>;
type ProxyBody = UnsyncBoxBody<Bytes, BoxError>;
type ErrorLogger = Arc<dyn Fn(String) + Send + Sync>;
type RouteProvider = Arc<dyn Fn() -> Vec<ProxyRoute> + Send + Sync>;

/// The subset of a route needed by the proxy.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProxyRoute {
    pub hostname: String,
    pub port: u16,
}

impl ProxyRoute {
    #[must_use]
    pub fn new(hostname: impl Into<String>, port: u16) -> Self {
        Self {
            hostname: hostname.into(),
            port,
        }
    }
}

impl From<(String, u16)> for ProxyRoute {
    fn from((hostname, port): (String, u16)) -> Self {
        Self { hostname, port }
    }
}

impl From<crate::routes::Route> for ProxyRoute {
    fn from(route: crate::routes::Route) -> Self {
        Self {
            hostname: route.hostname,
            port: route.port,
        }
    }
}

/// PEM-encoded TLS material accepted by the API.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TlsConfig {
    pub cert: Vec<u8>,
    pub key: Vec<u8>,
    pub ca: Option<Vec<u8>>,
}

/// Runtime proxy configuration.
#[derive(Clone)]
pub struct ProxyOptions {
    pub get_routes: RouteProvider,
    pub proxy_port: u16,
    pub tld: String,
    pub tlds: Vec<String>,
    pub strict: bool,
    pub bind_address: Option<IpAddr>,
    pub tls: Option<TlsConfig>,
    /// Separate plaintext redirect listener. Defaults to port 80. Set to
    /// `None` to disable it or `Some(0)` to request an ephemeral test port.
    pub http_redirect_port: Option<u16>,
    /// State directory containing the CA key and certificate. When set,
    /// unknown SNI names receive an exact certificate generated by
    /// [`crate::certs::generate_host_cert`] and cached for subsequent
    /// handshakes.
    pub sni_state_dir: Option<PathBuf>,
    pub on_error: ErrorLogger,
}

impl std::fmt::Debug for ProxyOptions {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ProxyOptions")
            .field("proxy_port", &self.proxy_port)
            .field("tld", &self.tld)
            .field("tlds", &self.tlds)
            .field("strict", &self.strict)
            .field("bind_address", &self.bind_address)
            .field("tls", &self.tls)
            .field("http_redirect_port", &self.http_redirect_port)
            .field("sni_state_dir", &self.sni_state_dir)
            .finish_non_exhaustive()
    }
}

impl ProxyOptions {
    #[must_use]
    pub fn new<F, I, R>(proxy_port: u16, get_routes: F) -> Self
    where
        F: Fn() -> I + Send + Sync + 'static,
        I: IntoIterator<Item = R>,
        R: Into<ProxyRoute>,
    {
        Self {
            get_routes: Arc::new(move || get_routes().into_iter().map(Into::into).collect()),
            proxy_port,
            tld: "localhost".to_owned(),
            tlds: Vec::new(),
            strict: true,
            bind_address: None,
            tls: None,
            http_redirect_port: Some(80),
            sni_state_dir: None,
            on_error: Arc::new(|message| eprintln!("{message}")),
        }
    }

    #[must_use]
    pub fn with_error_handler<F>(mut self, handler: F) -> Self
    where
        F: Fn(String) + Send + Sync + 'static,
    {
        self.on_error = Arc::new(handler);
        self
    }
}

/// Errors produced while creating or running a proxy.
#[derive(Debug, thiserror::Error)]
pub enum ProxyError {
    #[error("failed to bind Portless proxy: {0}")]
    Bind(#[source] std::io::Error),
    #[error("invalid TLS configuration: {0}")]
    Tls(String),
    #[error("failed to query proxy listener address: {0}")]
    LocalAddress(#[source] std::io::Error),
    #[error("proxy accept failed: {0}")]
    Accept(#[source] std::io::Error),
}

struct ExactSniResolver {
    default: Arc<CertifiedKey>,
    ca_pem: Vec<u8>,
    state_dir: Option<PathBuf>,
    cache: RwLock<HashMap<String, Arc<CertifiedKey>>>,
    generation_lock: Mutex<()>,
    on_error: ErrorLogger,
}

impl std::fmt::Debug for ExactSniResolver {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ExactSniResolver")
            .field("state_dir", &self.state_dir)
            .finish_non_exhaustive()
    }
}

impl ResolvesServerCert for ExactSniResolver {
    fn resolve(&self, hello: ClientHello<'_>) -> Option<Arc<CertifiedKey>> {
        let Some(server_name) = hello.server_name() else {
            return Some(Arc::clone(&self.default));
        };
        if let Some(certified_key) = self
            .cache
            .read()
            .ok()
            .and_then(|cache| cache.get(server_name).cloned())
        {
            return Some(certified_key);
        }
        let Some(state_dir) = self.state_dir.as_deref() else {
            return Some(Arc::clone(&self.default));
        };
        let Ok(_generation_guard) = self.generation_lock.lock() else {
            (self.on_error)(format!(
                "Failed to generate TLS certificate for {server_name}: certificate cache lock \
                 poisoned"
            ));
            return Some(Arc::clone(&self.default));
        };
        if let Some(certified_key) = self
            .cache
            .read()
            .ok()
            .and_then(|cache| cache.get(server_name).cloned())
        {
            return Some(certified_key);
        }

        let generated = crate::certs::generate_host_cert(state_dir, server_name)
            .map_err(|error| error.to_string())
            .and_then(|paths| {
                let cert = std::fs::read(paths.cert_path).map_err(|error| error.to_string())?;
                let key = std::fs::read(paths.key_path).map_err(|error| error.to_string())?;
                certified_key(&cert, &key, Some(&self.ca_pem)).map_err(|error| error.to_string())
            });
        match generated {
            Ok(certified_key) => {
                let certified_key = Arc::new(certified_key);
                if let Ok(mut cache) = self.cache.write() {
                    cache.insert(server_name.to_owned(), Arc::clone(&certified_key));
                }
                Some(certified_key)
            }
            Err(error) => {
                (self.on_error)(format!(
                    "Failed to generate TLS certificate for {server_name}: {error}"
                ));
                Some(Arc::clone(&self.default))
            }
        }
    }
}

fn build_tls_acceptor(
    tls: &TlsConfig,
    state_dir: Option<PathBuf>,
    on_error: &ErrorLogger,
) -> Result<TlsAcceptor, ProxyError> {
    let default = Arc::new(certified_key(&tls.cert, &tls.key, tls.ca.as_deref())?);
    let resolver = Arc::new(ExactSniResolver {
        default,
        ca_pem: tls.ca.clone().unwrap_or_default(),
        state_dir,
        cache: RwLock::new(HashMap::new()),
        generation_lock: Mutex::new(()),
        on_error: Arc::clone(on_error),
    });
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let mut config = ServerConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .map_err(|error| ProxyError::Tls(error.to_string()))?
        .with_no_client_auth()
        .with_cert_resolver(resolver);
    config.alpn_protocols = vec![b"h2".to_vec(), b"http/1.1".to_vec()];
    Ok(TlsAcceptor::from(Arc::new(config)))
}

fn certified_key(
    cert_pem: &[u8],
    key_pem: &[u8],
    ca_pem: Option<&[u8]>,
) -> Result<CertifiedKey, ProxyError> {
    let mut certificates = parse_certificates(cert_pem)?;
    if let Some(ca_pem) = ca_pem {
        certificates.extend(parse_certificates(ca_pem)?);
    }
    if certificates.is_empty() {
        return Err(ProxyError::Tls("certificate PEM is empty".to_owned()));
    }
    let key = parse_private_key(key_pem)?;
    let signing_key = rustls::crypto::ring::sign::any_supported_type(&key)
        .map_err(|error| ProxyError::Tls(error.to_string()))?;
    Ok(CertifiedKey::new(certificates, signing_key))
}

fn parse_certificates(pem: &[u8]) -> Result<Vec<CertificateDer<'static>>, ProxyError> {
    rustls_pemfile::certs(&mut Cursor::new(pem))
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| ProxyError::Tls(error.to_string()))
}

fn parse_private_key(pem: &[u8]) -> Result<PrivateKeyDer<'static>, ProxyError> {
    rustls_pemfile::private_key(&mut Cursor::new(pem))
        .map_err(|error| ProxyError::Tls(error.to_string()))?
        .ok_or_else(|| ProxyError::Tls("private-key PEM is empty".to_owned()))
}

/// A handle that requests graceful server shutdown.
#[derive(Clone, Debug)]
pub struct ProxyShutdown(watch::Sender<bool>);

impl ProxyShutdown {
    pub fn shutdown(&self) {
        let _ = self.0.send(true);
    }
}

/// A bound Portless proxy server.
pub struct ProxyServer {
    listener: TcpListener,
    redirect_listener: Option<TcpListener>,
    options: Arc<ProxyOptions>,
    tls_acceptor: Option<TlsAcceptor>,
    shutdown_tx: watch::Sender<bool>,
    shutdown_rx: watch::Receiver<bool>,
}

impl ProxyServer {
    /// Bind the configured port. With no explicit address, an IPv6 wildcard
    /// socket with `IPV6_V6ONLY=0` accepts both IPv4 and IPv6 loopback traffic.
    pub async fn bind(mut options: ProxyOptions) -> Result<Self, ProxyError> {
        let tls_acceptor = options
            .tls
            .as_ref()
            .map(|tls| build_tls_acceptor(tls, options.sni_state_dir.clone(), &options.on_error))
            .transpose()?;
        let listener = bind_listener(options.bind_address, options.proxy_port)
            .await
            .map_err(ProxyError::Bind)?;
        if options.proxy_port == 0 {
            options.proxy_port = listener
                .local_addr()
                .map_err(ProxyError::LocalAddress)?
                .port();
        }
        let redirect_listener = bind_redirect_listener(&options, tls_acceptor.is_some()).await;
        Ok(Self::from_parts(
            listener,
            redirect_listener,
            options,
            tls_acceptor,
        ))
    }

    pub fn from_listener(
        listener: TcpListener,
        mut options: ProxyOptions,
    ) -> Result<Self, ProxyError> {
        if options.proxy_port == 0 {
            options.proxy_port = listener
                .local_addr()
                .map_err(ProxyError::LocalAddress)?
                .port();
        }
        let tls_acceptor = options
            .tls
            .as_ref()
            .map(|tls| build_tls_acceptor(tls, options.sni_state_dir.clone(), &options.on_error))
            .transpose()?;
        Ok(Self::from_parts(listener, None, options, tls_acceptor))
    }

    fn from_parts(
        listener: TcpListener,
        redirect_listener: Option<TcpListener>,
        options: ProxyOptions,
        tls_acceptor: Option<TlsAcceptor>,
    ) -> Self {
        let (shutdown_tx, shutdown_rx) = watch::channel(false);
        Self {
            listener,
            redirect_listener,
            options: Arc::new(options),
            tls_acceptor,
            shutdown_tx,
            shutdown_rx,
        }
    }

    pub fn local_addr(&self) -> Result<SocketAddr, ProxyError> {
        self.listener.local_addr().map_err(ProxyError::LocalAddress)
    }

    /// Address of the best-effort separate plaintext redirect listener.
    pub fn redirect_local_addr(&self) -> Result<Option<SocketAddr>, ProxyError> {
        self.redirect_listener
            .as_ref()
            .map(TcpListener::local_addr)
            .transpose()
            .map_err(ProxyError::LocalAddress)
    }

    #[must_use]
    pub fn shutdown_handle(&self) -> ProxyShutdown {
        ProxyShutdown(self.shutdown_tx.clone())
    }

    /// Serve until [`ProxyShutdown::shutdown`] is called.
    pub async fn run(self) -> Result<(), ProxyError> {
        self.run_inner(std::future::pending::<()>()).await
    }

    /// Serve until either the handle is used or the supplied future completes.
    pub async fn run_until<F>(self, shutdown: F) -> Result<(), ProxyError>
    where
        F: Future<Output = ()>,
    {
        self.run_inner(shutdown).await
    }

    async fn run_inner<F>(mut self, shutdown: F) -> Result<(), ProxyError>
    where
        F: Future<Output = ()>,
    {
        let mut connections = JoinSet::new();
        let client: Client<HttpConnector, Incoming> =
            Client::builder(TokioExecutor::new()).build(HttpConnector::new());
        tokio::pin!(shutdown);

        loop {
            tokio::select! {
                accepted = self.listener.accept() => {
                    let (stream, remote_addr) = accepted.map_err(ProxyError::Accept)?;
                    let options = Arc::clone(&self.options);
                    let client = client.clone();
                    let connection_shutdown = self.shutdown_rx.clone();
                    let tls_acceptor = self.tls_acceptor.clone();
                    connections.spawn(async move {
                        serve_accepted_connection(
                            stream,
                            remote_addr,
                            options,
                            client,
                            tls_acceptor,
                            connection_shutdown,
                        )
                        .await;
                    });
                }
                redirected = accept_optional(self.redirect_listener.as_ref()) => {
                    match redirected {
                        Ok((stream, _)) => {
                            let connection_shutdown = self.shutdown_rx.clone();
                            let https_port = self.options.proxy_port;
                            connections.spawn(async move {
                                serve_plain_redirect(stream, https_port, connection_shutdown).await;
                            });
                        }
                        Err(error) => {
                            (self.options.on_error)(format!(
                                "HTTP redirect listener stopped accepting connections: {error}"
                            ));
                            self.redirect_listener = None;
                        }
                    }
                }
                _ = self.shutdown_rx.changed() => break,
                () = &mut shutdown => {
                    let _ = self.shutdown_tx.send(true);
                    break;
                }
            }
        }

        while tokio::time::timeout(Duration::from_secs(5), connections.join_next())
            .await
            .is_ok_and(|joined| joined.is_some())
        {}
        Ok(())
    }
}

async fn accept_optional(
    listener: Option<&TcpListener>,
) -> std::io::Result<(tokio::net::TcpStream, SocketAddr)> {
    match listener {
        Some(listener) => listener.accept().await,
        None => std::future::pending().await,
    }
}

async fn bind_redirect_listener(options: &ProxyOptions, tls_enabled: bool) -> Option<TcpListener> {
    let redirect_port = options.http_redirect_port?;
    if !tls_enabled || options.proxy_port == 80 {
        return None;
    }
    match bind_listener(options.bind_address, redirect_port).await {
        Ok(listener) => Some(listener),
        Err(error) => {
            (options.on_error)(format!(
                "Could not bind HTTP redirect listener on port {redirect_port}: {error}"
            ));
            None
        }
    }
}

async fn serve_accepted_connection(
    stream: tokio::net::TcpStream,
    remote_addr: SocketAddr,
    options: Arc<ProxyOptions>,
    client: Client<HttpConnector, Incoming>,
    tls_acceptor: Option<TlsAcceptor>,
    mut shutdown: watch::Receiver<bool>,
) {
    let Some(tls_acceptor) = tls_acceptor else {
        serve_http1(stream, remote_addr, options, client, false, shutdown).await;
        return;
    };

    let mut first = [0_u8; 1];
    let peeked = tokio::select! {
        result = stream.peek(&mut first) => result,
        _ = shutdown.changed() => return,
    };
    match peeked {
        Ok(0) | Err(_) => {}
        Ok(_) if first[0] != 0x16 => {
            serve_plain_redirect(stream, options.proxy_port, shutdown).await;
        }
        Ok(_) => match tokio::select! {
            result = tls_acceptor.accept(stream) => Some(result),
            _ = shutdown.changed() => None,
        } {
            None => {}
            Some(Ok(tls_stream)) => {
                let protocol = tls_stream.get_ref().1.alpn_protocol();
                if protocol == Some(b"h2") {
                    serve_http2(tls_stream, remote_addr, options, client, shutdown).await;
                } else {
                    serve_http1(tls_stream, remote_addr, options, client, true, shutdown).await;
                }
            }
            Some(Err(error)) => {
                (options.on_error)(format!("TLS handshake failed: {error}"));
            }
        },
    }
}

async fn serve_http1<I>(
    io: I,
    remote_addr: SocketAddr,
    options: Arc<ProxyOptions>,
    client: Client<HttpConnector, Incoming>,
    tls: bool,
    mut shutdown: watch::Receiver<bool>,
) where
    I: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin + Send + 'static,
{
    let service = service_fn(move |request| {
        proxy_request(
            request,
            remote_addr,
            Arc::clone(&options),
            client.clone(),
            tls,
        )
    });
    let connection = hyper::server::conn::http1::Builder::new()
        .serve_connection(TokioIo::new(io), service)
        .with_upgrades();
    tokio::pin!(connection);
    tokio::select! {
        _ = &mut connection => {}
        _ = shutdown.changed() => {
            connection.as_mut().graceful_shutdown();
            let _ = connection.await;
        }
    }
}

async fn serve_http2<I>(
    io: I,
    remote_addr: SocketAddr,
    options: Arc<ProxyOptions>,
    client: Client<HttpConnector, Incoming>,
    mut shutdown: watch::Receiver<bool>,
) where
    I: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin + Send + 'static,
{
    let service = service_fn(move |request| {
        proxy_request(
            request,
            remote_addr,
            Arc::clone(&options),
            client.clone(),
            true,
        )
    });
    let connection = hyper::server::conn::http2::Builder::new(TokioExecutor::new())
        .serve_connection(TokioIo::new(io), service);
    tokio::pin!(connection);
    tokio::select! {
        _ = &mut connection => {}
        _ = shutdown.changed() => {
            connection.as_mut().graceful_shutdown();
            let _ = connection.await;
        }
    }
}

async fn serve_plain_redirect(
    io: tokio::net::TcpStream,
    https_port: u16,
    mut shutdown: watch::Receiver<bool>,
) {
    let service = service_fn(move |request: Request<Incoming>| async move {
        let host = request_host(&request);
        let path = request
            .uri()
            .path_and_query()
            .map_or("/", hyper::http::uri::PathAndQuery::as_str);
        Ok::<_, Infallible>(https_redirect(&host, path, https_port))
    });
    let connection =
        hyper::server::conn::http1::Builder::new().serve_connection(TokioIo::new(io), service);
    tokio::pin!(connection);
    tokio::select! {
        _ = &mut connection => {}
        _ = shutdown.changed() => {
            connection.as_mut().graceful_shutdown();
            let _ = connection.await;
        }
    }
}

async fn bind_listener(address: Option<IpAddr>, port: u16) -> std::io::Result<TcpListener> {
    match address {
        Some(IpAddr::V4(ip)) => TcpListener::bind((ip, port)).await,
        Some(IpAddr::V6(ip)) => TcpListener::bind((ip, port)).await,
        None => {
            let socket = TcpSocket::new_v6()?;
            match socket.bind(SocketAddr::new(IpAddr::V6(Ipv6Addr::UNSPECIFIED), port)) {
                Ok(()) => socket.listen(1024),
                Err(_) => TcpListener::bind((Ipv4Addr::UNSPECIFIED, port)).await,
            }
        }
    }
}

async fn proxy_request(
    mut request: Request<Incoming>,
    remote_addr: SocketAddr,
    options: Arc<ProxyOptions>,
    client: Client<HttpConnector, Incoming>,
    tls: bool,
) -> Result<Response<ProxyBody>, Infallible> {
    let client_http2 = request.version() == hyper::Version::HTTP_2;
    let host_header = request_host(&request);
    let host = hostname(&host_header);

    if host.is_empty() {
        return Ok(text_response(
            StatusCode::BAD_REQUEST,
            "Missing Host header",
        ));
    }

    let hops = request
        .headers()
        .get(PORTLESS_HOPS_HEADER)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.parse::<u8>().ok())
        .unwrap_or(0);
    if hops >= MAX_PROXY_HOPS {
        (options.on_error)(format!(
            "Loop detected for {host}: request has passed through portless {hops} times. This \
             usually means a backend is proxying back through portless without rewriting the Host \
             header. If you use Vite/webpack proxy, set changeOrigin: true."
        ));
        return Ok(loop_response(hops, &options, tls));
    }

    let routes = (options.get_routes)();
    let Some(route) = find_route(&routes, &host, options.strict) else {
        return Ok(not_found_response(&host, &routes, &options, tls));
    };

    let is_upgrade = is_websocket_upgrade(request.headers());
    let client_upgrade = is_upgrade.then(|| hyper::upgrade::on(&mut request));
    add_forwarded_headers(request.headers_mut(), &host_header, remote_addr, tls);
    if let Ok(value) = hyper::header::HeaderValue::from_str(&(hops + 1).to_string()) {
        request.headers_mut().insert(PORTLESS_HOPS_HEADER, value);
    }
    if let (false, Ok(value)) = (
        request.headers().contains_key(HOST),
        hyper::header::HeaderValue::from_str(&host_header),
    ) {
        request.headers_mut().insert(HOST, value);
    }

    let path = request
        .uri()
        .path_and_query()
        .map_or("/", hyper::http::uri::PathAndQuery::as_str);
    let target = format!("http://localhost:{}{path}", route.port);
    let Ok(uri) = target.parse::<Uri>() else {
        (options.on_error)(format!(
            "Proxy error for {host_header}: invalid backend URI"
        ));
        return Ok(bad_gateway_response(false));
    };
    *request.uri_mut() = uri;
    *request.version_mut() = hyper::Version::HTTP_11;

    match client.request(request).await {
        Ok(mut response) => {
            if client_http2 {
                for header in HOP_BY_HOP_HEADERS {
                    response.headers_mut().remove(header);
                }
            }
            response.headers_mut().insert(
                PORTLESS_HEADER,
                hyper::header::HeaderValue::from_static("1"),
            );
            if let (StatusCode::SWITCHING_PROTOCOLS, Some(client_upgrade)) =
                (response.status(), client_upgrade)
            {
                let backend_upgrade = hyper::upgrade::on(&mut response);
                tokio::spawn(async move {
                    if let (Ok(client_stream), Ok(backend_stream)) =
                        (client_upgrade.await, backend_upgrade.await)
                    {
                        let mut client_stream = TokioIo::new(client_stream);
                        let mut backend_stream = TokioIo::new(backend_stream);
                        let _ = copy_bidirectional(&mut client_stream, &mut backend_stream).await;
                    }
                });
            }
            Ok(response.map(|body| {
                body.map_err(|error| -> BoxError { Box::new(error) })
                    .boxed_unsync()
            }))
        }
        Err(error) => {
            (options.on_error)(format!("Proxy error for {host_header}: {error}"));
            Ok(bad_gateway_response(error.is_connect()))
        }
    }
}

fn request_host(request: &Request<Incoming>) -> String {
    request
        .headers()
        .get(HOST)
        .and_then(|value| value.to_str().ok())
        .or_else(|| {
            request
                .uri()
                .authority()
                .map(hyper::http::uri::Authority::as_str)
        })
        .unwrap_or_default()
        .to_owned()
}

fn hostname(authority: &str) -> String {
    authority
        .parse::<hyper::http::uri::Authority>()
        .map_or_else(
            |_| authority.split(':').next().unwrap_or_default().to_owned(),
            |parsed| parsed.host().to_owned(),
        )
        .trim_matches(['[', ']'])
        .to_ascii_lowercase()
}

fn find_route<'a>(routes: &'a [ProxyRoute], host: &str, strict: bool) -> Option<&'a ProxyRoute> {
    routes
        .iter()
        .find(|route| route.hostname.eq_ignore_ascii_case(host))
        .or_else(|| {
            (!strict).then(|| {
                routes.iter().find(|route| {
                    host.len() > route.hostname.len()
                        && host
                            .get(host.len() - route.hostname.len()..)
                            .is_some_and(|suffix| suffix.eq_ignore_ascii_case(&route.hostname))
                        && host.as_bytes().get(host.len() - route.hostname.len() - 1) == Some(&b'.')
                })
            })?
        })
}

fn add_forwarded_headers(headers: &mut HeaderMap, host: &str, remote_addr: SocketAddr, tls: bool) {
    let remote = remote_addr.ip().to_string();
    append_or_insert(headers, "x-forwarded-for", &remote);
    insert_if_absent(
        headers,
        "x-forwarded-proto",
        if tls { "https" } else { "http" },
    );
    insert_if_absent(headers, "x-forwarded-host", host);
    let forwarded_port = host
        .parse::<hyper::http::uri::Authority>()
        .ok()
        .and_then(|authority| authority.port_u16())
        .map_or_else(
            || {
                if tls {
                    "443".to_owned()
                } else {
                    "80".to_owned()
                }
            },
            |p| p.to_string(),
        );
    insert_if_absent(headers, "x-forwarded-port", &forwarded_port);
}

fn append_or_insert(headers: &mut HeaderMap, name: &'static str, value: &str) {
    let combined = headers
        .get(name)
        .and_then(|existing| existing.to_str().ok())
        .map_or_else(
            || value.to_owned(),
            |existing| format!("{existing}, {value}"),
        );
    if let Ok(value) = hyper::header::HeaderValue::from_str(&combined) {
        headers.insert(name, value);
    }
}

fn insert_if_absent(headers: &mut HeaderMap, name: &'static str, value: &str) {
    if let (false, Ok(value)) = (
        headers.contains_key(name),
        hyper::header::HeaderValue::from_str(value),
    ) {
        headers.insert(name, value);
    }
}

fn is_websocket_upgrade(headers: &HeaderMap) -> bool {
    headers
        .get(hyper::header::UPGRADE)
        .and_then(|value| value.to_str().ok())
        .is_some_and(|value| value.eq_ignore_ascii_case("websocket"))
        && headers
            .get(hyper::header::CONNECTION)
            .and_then(|value| value.to_str().ok())
            .is_some_and(|value| {
                value
                    .split(',')
                    .any(|token| token.trim().eq_ignore_ascii_case("upgrade"))
            })
}

fn empty_body() -> ProxyBody {
    Full::new(Bytes::new())
        .map_err(|never| match never {})
        .boxed_unsync()
}

fn body(value: impl Into<Bytes>) -> ProxyBody {
    Full::new(value.into())
        .map_err(|never| match never {})
        .boxed_unsync()
}

fn response(
    status: StatusCode,
    content_type: &str,
    content: impl Into<Bytes>,
) -> Response<ProxyBody> {
    let mut response = Response::new(body(content));
    *response.status_mut() = status;
    response.headers_mut().insert(
        PORTLESS_HEADER,
        hyper::header::HeaderValue::from_static("1"),
    );
    if let Ok(value) = hyper::header::HeaderValue::from_str(content_type) {
        response.headers_mut().insert(CONTENT_TYPE, value);
    }
    response
}

fn text_response(status: StatusCode, content: &str) -> Response<ProxyBody> {
    response(status, "text/plain", content.to_owned())
}

fn loop_response(hops: u8, options: &ProxyOptions, tls: bool) -> Response<ProxyBody> {
    let primary_tld = options
        .tlds
        .first()
        .filter(|value| !value.is_empty())
        .unwrap_or(&options.tld);
    let scheme = if tls { "https" } else { "http" };
    let port = if tls { "" } else { ":&lt;port&gt;" };
    let body = format!(
        r#"<div class="content"><p class="desc">This request has passed through portless {hops} times. This usually means a dev server (Vite, webpack, etc.) is proxying requests back through portless without rewriting the Host header.</p><div class="section"><p class="label">Fix: add changeOrigin to your proxy config</p><pre class="terminal">proxy: {{
  "/api": {{
    target: "{scheme}://&lt;backend&gt;.{}{port}",
    changeOrigin: true,
  }},
}}</pre></div></div>"#,
        escape_html(primary_tld)
    );
    response(
        StatusCode::LOOP_DETECTED,
        "text/html",
        render_page(508, "Loop Detected", &body),
    )
}

fn not_found_response(
    host: &str,
    routes: &[ProxyRoute],
    options: &ProxyOptions,
    tls: bool,
) -> Response<ProxyBody> {
    let escaped_host = escape_html(host);
    let suffixes = effective_tlds(options);
    let stripped = suffixes
        .iter()
        .find_map(|suffix| host.strip_suffix(suffix))
        .unwrap_or(host);
    let routes_list = if routes.is_empty() {
        r#"<p class="empty">No apps running.</p>"#.to_owned()
    } else {
        let mut items = String::new();
        for route in routes {
            let _ = write!(
                items,
                r#"<li><a href="{}" class="card-link"><span class="name">{}</span><span class="meta"><code class="port">127.0.0.1:{}</code><span class="arrow">{ARROW_SVG}</span></span></a></li>"#,
                escape_html(&format_url(&route.hostname, options.proxy_port, tls)),
                escape_html(&route.hostname),
                route.port
            );
        }
        format!(
            r#"<div class="section"><p class="label">Active apps</p><ul class="card">{items}</ul></div>"#
        )
    };
    let content = format!(
        r#"<div class="content"><p class="desc">No app registered for <strong>{escaped_host}</strong></p>{routes_list}<div class="section"><p class="label">Start one</p><div class="terminal"><span class="prompt">$</span> portless {} your-command</div></div></div>"#,
        escape_html(stripped)
    );
    response(
        StatusCode::NOT_FOUND,
        "text/html",
        render_page(404, "Not Found", &content),
    )
}

fn effective_tlds(options: &ProxyOptions) -> Vec<String> {
    let tlds = if options.tlds.is_empty() {
        vec![options.tld.as_str()]
    } else {
        options.tlds.iter().map(String::as_str).collect()
    };
    let mut suffixes = Vec::new();
    for tld in tlds {
        let suffix = format!(".{tld}");
        if !suffixes.contains(&suffix) {
            suffixes.push(suffix);
        }
    }
    suffixes
}

fn bad_gateway_response(connection_refused: bool) -> Response<ProxyBody> {
    let detail = if connection_refused {
        "The target app is not responding. It may have crashed."
    } else {
        "The target app may not be running."
    };
    let content = format!(r#"<div class="content"><p class="desc">{detail}</p></div>"#);
    response(
        StatusCode::BAD_GATEWAY,
        "text/html",
        render_page(502, "Bad Gateway", &content),
    )
}

fn format_url(hostname: &str, port: u16, tls: bool) -> String {
    let scheme = if tls { "https" } else { "http" };
    let default_port = if tls { 443 } else { 80 };
    if port == default_port {
        format!("{scheme}://{hostname}")
    } else {
        format!("{scheme}://{hostname}:{port}")
    }
}

fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

/// Create the small redirect response used by TLS frontends.
#[must_use]
pub fn https_redirect(host: &str, path: &str, https_port: u16) -> Response<ProxyBody> {
    let hostname = match hostname(host) {
        hostname if hostname.is_empty() => "localhost".to_owned(),
        hostname => hostname,
    };
    let port = if https_port == 443 {
        String::new()
    } else {
        format!(":{https_port}")
    };
    let location = format!("https://{hostname}{port}{path}");
    let mut response = Response::new(empty_body());
    *response.status_mut() = StatusCode::FOUND;
    if let Ok(value) = hyper::header::HeaderValue::from_str(&location) {
        response
            .headers_mut()
            .insert(hyper::header::LOCATION, value);
    }
    response.headers_mut().insert(
        PORTLESS_HEADER,
        hyper::header::HeaderValue::from_static("1"),
    );
    response
}

#[cfg(test)]
mod tests {
    use std::{
        convert::Infallible,
        fs,
        io::Cursor,
        net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr},
        sync::{Arc, Mutex},
    };

    use http_body_util::{BodyExt, Full};
    use hyper::{HeaderMap, Request, Response, body::Bytes, header::HOST, service::service_fn};
    use hyper_util::rt::{TokioExecutor, TokioIo};
    use rustls::{
        ClientConfig, RootCertStore,
        pki_types::{CertificateDer, ServerName},
    };
    use tokio::{io::AsyncWriteExt, net::TcpListener};
    use tokio_rustls::TlsConnector;

    use super::{
        MAX_PROXY_HOPS, PORTLESS_HEADER, ProxyError, ProxyOptions, ProxyRoute, ProxyServer,
        TlsConfig, escape_html, find_route, format_url,
    };

    async fn backend() -> (u16, tokio::task::JoinHandle<()>, Arc<Mutex<Vec<HeaderMap>>>) {
        let listener = TcpListener::bind((Ipv4Addr::LOCALHOST, 0))
            .await
            .expect("backend binds");
        let port = listener.local_addr().expect("backend address").port();
        let seen = Arc::new(Mutex::new(Vec::new()));
        let task_seen = Arc::clone(&seen);
        let task = tokio::spawn(async move {
            while let Ok((stream, _)) = listener.accept().await {
                let task_seen = Arc::clone(&task_seen);
                tokio::spawn(async move {
                    let service = service_fn(move |request: Request<hyper::body::Incoming>| {
                        task_seen
                            .lock()
                            .expect("headers lock")
                            .push(request.headers().clone());
                        async {
                            Ok::<_, Infallible>(Response::new(Full::new(Bytes::from_static(
                                b"hello from backend",
                            ))))
                        }
                    });
                    let _ = hyper::server::conn::http1::Builder::new()
                        .serve_connection(TokioIo::new(stream), service)
                        .await;
                });
            }
        });
        (port, task, seen)
    }

    async fn start_proxy(
        options: ProxyOptions,
    ) -> (
        SocketAddr,
        super::ProxyShutdown,
        tokio::task::JoinHandle<()>,
    ) {
        let mut options = options;
        options.bind_address = Some(IpAddr::V4(Ipv4Addr::LOCALHOST));
        let server = ProxyServer::bind(options).await.expect("proxy binds");
        let address = server.local_addr().expect("proxy address");
        let shutdown = server.shutdown_handle();
        let task = tokio::spawn(async move {
            server.run().await.expect("proxy runs");
        });
        (address, shutdown, task)
    }

    async fn raw_request(address: SocketAddr, request: &str) -> String {
        let mut stream = tokio::net::TcpStream::connect(address)
            .await
            .expect("connects to proxy");
        stream
            .write_all(request.as_bytes())
            .await
            .expect("writes request");
        let mut response = Vec::new();
        tokio::io::AsyncReadExt::read_to_end(&mut stream, &mut response)
            .await
            .expect("reads response");
        String::from_utf8(response).expect("HTTP is utf8")
    }

    fn tls_fixture() -> (tempfile::TempDir, TlsConfig, Vec<CertificateDer<'static>>) {
        let state_dir = tempfile::tempdir().expect("creates state directory");
        let paths = crate::certs::ensure_certs(state_dir.path()).expect("creates certificates");
        let cert = fs::read(paths.cert_path).expect("reads server certificate");
        let key = fs::read(paths.key_path).expect("reads server key");
        let ca = fs::read(paths.ca_path).expect("reads CA certificate");
        let roots = rustls_pemfile::certs(&mut Cursor::new(&ca))
            .collect::<Result<Vec<_>, _>>()
            .expect("parses CA certificate");
        (
            state_dir,
            TlsConfig {
                cert,
                key,
                ca: Some(ca),
            },
            roots,
        )
    }

    fn tls_connector(roots: Vec<CertificateDer<'static>>, alpn: &[u8]) -> TlsConnector {
        let mut root_store = RootCertStore::empty();
        root_store.add_parsable_certificates(roots);
        let provider = Arc::new(rustls::crypto::ring::default_provider());
        let mut config = ClientConfig::builder_with_provider(provider)
            .with_safe_default_protocol_versions()
            .expect("supports TLS versions")
            .with_root_certificates(root_store)
            .with_no_client_auth();
        config.alpn_protocols = vec![alpn.to_vec()];
        TlsConnector::from(Arc::new(config))
    }

    #[test]
    fn exact_route_wins_and_wildcard_obeys_strict() {
        let routes = vec![
            ProxyRoute::new("app.localhost", 3000),
            ProxyRoute::new("tenant.app.localhost", 3001),
        ];
        assert_eq!(
            find_route(&routes, "tenant.app.localhost", false).map(|route| route.port),
            Some(3001)
        );
        assert!(find_route(&routes, "other.app.localhost", true).is_none());
        assert_eq!(
            find_route(&routes, "other.app.localhost", false).map(|route| route.port),
            Some(3000)
        );
        assert!(find_route(&routes, "notapp.localhost", false).is_none());
    }

    #[test]
    fn utility_output_matches_node_port() {
        assert_eq!(
            escape_html(r#"<a x="'">&"#),
            "&lt;a x=&quot;&#39;&quot;&gt;&amp;"
        );
        assert_eq!(
            format_url("app.localhost", 80, false),
            "http://app.localhost"
        );
        assert_eq!(
            format_url("app.localhost", 1355, false),
            "http://app.localhost:1355"
        );
    }

    #[tokio::test]
    async fn proxies_stream_and_adds_forwarded_headers() {
        let (backend_port, backend_task, seen) = backend().await;
        let options = ProxyOptions::new(0, move || {
            vec![ProxyRoute::new("app.localhost", backend_port)]
        });
        let (address, shutdown, proxy_task) = start_proxy(options).await;
        let response = raw_request(
            address,
            "GET /hello HTTP/1.1\r\nHost: app.localhost\r\nConnection: close\r\n\r\n",
        )
        .await;
        assert!(response.starts_with("HTTP/1.1 200"));
        assert!(response.to_ascii_lowercase().contains("x-portless: 1"));
        assert!(response.ends_with("hello from backend"));
        {
            let headers = seen.lock().expect("headers lock");
            assert_eq!(headers[0]["x-forwarded-host"], "app.localhost");
            assert_eq!(headers[0]["x-forwarded-proto"], "http");
            assert_eq!(headers[0]["x-forwarded-port"], "80");
            assert_eq!(headers[0]["x-portless-hops"], "1");
        }
        shutdown.shutdown();
        proxy_task.await.expect("proxy joins");
        backend_task.abort();
    }

    #[tokio::test]
    async fn renders_400_404_502_and_508_pages() {
        let options = ProxyOptions::new(0, || vec![ProxyRoute::new("dead.localhost", 9)]);
        let (address, shutdown, proxy_task) = start_proxy(options).await;

        let missing = raw_request(address, "GET / HTTP/1.0\r\n\r\n").await;
        assert!(
            missing
                .lines()
                .next()
                .is_some_and(|line| line.contains(" 400 "))
        );
        assert!(missing.contains("Missing Host header"));

        let missing_route = raw_request(
            address,
            "GET / HTTP/1.1\r\nHost: unknown.localhost\r\nConnection: close\r\n\r\n",
        )
        .await;
        assert!(missing_route.starts_with("HTTP/1.1 404"));
        assert!(missing_route.contains("Not Found"));

        let dead = raw_request(
            address,
            "GET / HTTP/1.1\r\nHost: dead.localhost\r\nConnection: close\r\n\r\n",
        )
        .await;
        assert!(dead.starts_with("HTTP/1.1 502"));
        assert!(dead.contains("Bad Gateway"));

        let looped = raw_request(
            address,
            &format!(
                "GET / HTTP/1.1\r\nHost: dead.localhost\r\nx-portless-hops: \
                 {MAX_PROXY_HOPS}\r\nConnection: close\r\n\r\n"
            ),
        )
        .await;
        assert!(looped.starts_with("HTTP/1.1 508"));
        assert!(looped.contains("Loop Detected"));
        assert!(looped.contains("changeOrigin"));
        assert!(
            looped
                .to_ascii_lowercase()
                .contains(&format!("{}: 1", PORTLESS_HEADER.to_ascii_lowercase()))
        );

        shutdown.shutdown();
        proxy_task.await.expect("proxy joins");
    }

    #[tokio::test]
    async fn invalid_tls_configuration_fails_closed() {
        let mut options = ProxyOptions::new(0, Vec::<ProxyRoute>::new);
        options.tls = Some(TlsConfig {
            cert: vec![1],
            key: vec![2],
            ca: None,
        });
        assert!(matches!(
            ProxyServer::bind(options).await,
            Err(ProxyError::Tls(_))
        ));
    }

    #[tokio::test]
    async fn separate_http_listener_redirects_and_shuts_down_with_proxy() {
        let (_state_dir, tls, _roots) = tls_fixture();
        let mut options = ProxyOptions::new(0, Vec::<ProxyRoute>::new);
        options.bind_address = Some(IpAddr::V4(Ipv4Addr::LOCALHOST));
        options.tls = Some(tls);
        options.http_redirect_port = Some(0);
        let server = ProxyServer::bind(options).await.expect("TLS proxy binds");
        let https_port = server.local_addr().expect("proxy address").port();
        let redirect_address = server
            .redirect_local_addr()
            .expect("redirect address query succeeds")
            .expect("redirect listener binds");
        let shutdown = server.shutdown_handle();
        let proxy_task = tokio::spawn(async move {
            server.run().await.expect("proxy runs");
        });

        let response = raw_request(
            redirect_address,
            "GET /from-port-80 HTTP/1.1\r\nHost: app.localhost\r\nConnection: close\r\n\r\n",
        )
        .await;
        assert!(response.starts_with("HTTP/1.1 302"));
        assert!(response.to_ascii_lowercase().contains(&format!(
            "location: https://app.localhost:{https_port}/from-port-80"
        )));

        shutdown.shutdown();
        proxy_task.await.expect("proxy joins");
        assert!(
            tokio::net::TcpStream::connect(redirect_address)
                .await
                .is_err()
        );
    }

    #[tokio::test]
    async fn redirect_bind_failure_does_not_fail_tls_proxy() {
        let occupied = TcpListener::bind((Ipv4Addr::LOCALHOST, 0))
            .await
            .expect("occupies redirect port");
        let occupied_port = occupied.local_addr().expect("occupied address").port();
        let (_state_dir, tls, _roots) = tls_fixture();
        let errors = Arc::new(Mutex::new(Vec::new()));
        let captured_errors = Arc::clone(&errors);
        let mut options =
            ProxyOptions::new(0, Vec::<ProxyRoute>::new).with_error_handler(move |message| {
                captured_errors.lock().expect("error lock").push(message);
            });
        options.bind_address = Some(IpAddr::V4(Ipv4Addr::LOCALHOST));
        options.tls = Some(tls);
        options.http_redirect_port = Some(occupied_port);

        let server = ProxyServer::bind(options)
            .await
            .expect("main TLS proxy still binds");
        assert!(
            server
                .redirect_local_addr()
                .expect("address query")
                .is_none()
        );
        assert!(
            errors
                .lock()
                .expect("error lock")
                .iter()
                .any(|message| message.contains("Could not bind HTTP redirect listener"))
        );
    }

    #[tokio::test]
    async fn supplied_certificate_without_ca_or_sni_generation_serves_tls() {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};

        let (_state_dir, mut tls, roots) = tls_fixture();
        tls.ca = None;
        let mut options = ProxyOptions::new(0, Vec::<ProxyRoute>::new);
        options.bind_address = Some(IpAddr::V4(Ipv4Addr::LOCALHOST));
        options.tls = Some(tls);
        options.http_redirect_port = None;
        assert!(options.sni_state_dir.is_none());
        let server = ProxyServer::bind(options)
            .await
            .expect("custom TLS proxy binds");
        let address = server.local_addr().expect("proxy address");
        let shutdown = server.shutdown_handle();
        let proxy_task = tokio::spawn(async move {
            server.run().await.expect("proxy runs");
        });

        let tcp = tokio::net::TcpStream::connect(address)
            .await
            .expect("connects to TLS proxy");
        let mut stream = tls_connector(roots, b"http/1.1")
            .connect(
                ServerName::try_from("localhost").expect("valid server name"),
                tcp,
            )
            .await
            .expect("validates supplied certificate");
        stream
            .write_all(b"GET / HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n")
            .await
            .expect("writes HTTPS request");
        let mut response = Vec::new();
        stream
            .read_to_end(&mut response)
            .await
            .expect("reads HTTPS response");
        assert!(String::from_utf8_lossy(&response).starts_with("HTTP/1.1 404"));

        shutdown.shutdown();
        proxy_task.await.expect("proxy joins");
    }

    #[tokio::test]
    async fn tls_listener_redirects_plain_http_and_serves_exact_sni_http2() {
        let (backend_port, backend_task, seen) = backend().await;
        let (state_dir, tls, roots) = tls_fixture();
        let mut options = ProxyOptions::new(0, move || {
            vec![ProxyRoute::new("deep.app.localhost", backend_port)]
        });
        options.bind_address = Some(IpAddr::V4(Ipv4Addr::LOCALHOST));
        options.tls = Some(tls);
        options.sni_state_dir = Some(state_dir.path().to_path_buf());
        options.http_redirect_port = None;
        let server = ProxyServer::bind(options).await.expect("TLS proxy binds");
        let address = server.local_addr().expect("proxy address");
        let shutdown = server.shutdown_handle();
        let proxy_task = tokio::spawn(async move {
            server.run().await.expect("proxy runs");
        });

        let redirect = raw_request(
            address,
            "GET /docs?q=1 HTTP/1.1\r\nHost: deep.app.localhost\r\nConnection: close\r\n\r\n",
        )
        .await;
        assert!(redirect.starts_with("HTTP/1.1 302"));
        assert!(
            redirect.to_ascii_lowercase().contains(&format!(
                "location: https://deep.app.localhost:{}/docs?q=1",
                address.port()
            )),
            "{redirect}"
        );

        let tcp = tokio::net::TcpStream::connect(address)
            .await
            .expect("connects to TLS proxy");
        let server_name =
            ServerName::try_from("deep.app.localhost").expect("valid exact server name");
        let tls_stream = tls_connector(roots, b"h2")
            .connect(server_name, tcp)
            .await
            .expect("validates exact SNI certificate");
        assert_eq!(
            tls_stream.get_ref().1.alpn_protocol(),
            Some(b"h2".as_slice())
        );
        let (mut sender, connection) =
            hyper::client::conn::http2::handshake(TokioExecutor::new(), TokioIo::new(tls_stream))
                .await
                .expect("performs HTTP/2 handshake");
        let connection_task = tokio::spawn(async move {
            connection.await.expect("HTTP/2 connection runs");
        });
        let request = Request::builder()
            .uri("https://deep.app.localhost/hello")
            .body(Full::new(Bytes::new()))
            .expect("builds HTTP/2 request");
        let response = sender
            .send_request(request)
            .await
            .expect("sends HTTP/2 request");
        assert_eq!(response.version(), hyper::Version::HTTP_2);
        assert_eq!(response.status(), hyper::StatusCode::OK);
        let body = response
            .into_body()
            .collect()
            .await
            .expect("reads streamed response")
            .to_bytes();
        assert_eq!(body, "hello from backend");
        {
            let headers = seen.lock().expect("headers lock");
            assert_eq!(headers[0][HOST], "deep.app.localhost");
            assert_eq!(headers[0]["x-forwarded-host"], "deep.app.localhost");
            assert_eq!(headers[0]["x-forwarded-proto"], "https");
            assert_eq!(headers[0]["x-forwarded-port"], "443");
        }
        drop(sender);
        connection_task.await.expect("HTTP/2 task joins");

        shutdown.shutdown();
        proxy_task.await.expect("proxy joins");
        backend_task.abort();
    }

    #[tokio::test]
    async fn default_listener_accepts_ipv4_and_ipv6_loopback() {
        let server = ProxyServer::bind(ProxyOptions::new(0, Vec::<ProxyRoute>::new))
            .await
            .expect("dual-stack proxy binds");
        let port = server.local_addr().expect("proxy address").port();
        let shutdown = server.shutdown_handle();
        let proxy_task = tokio::spawn(async move {
            server.run().await.expect("proxy runs");
        });

        for ip in [
            IpAddr::V4(Ipv4Addr::LOCALHOST),
            IpAddr::V6(Ipv6Addr::LOCALHOST),
        ] {
            let response = raw_request(
                SocketAddr::new(ip, port),
                "GET / HTTP/1.1\r\nHost: unknown.localhost\r\nConnection: close\r\n\r\n",
            )
            .await;
            assert!(response.starts_with("HTTP/1.1 404"));
        }

        shutdown.shutdown();
        proxy_task.await.expect("proxy joins");
    }

    #[tokio::test]
    async fn relays_websocket_upgrade_and_stream_bytes() {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};

        let backend = TcpListener::bind((Ipv4Addr::LOCALHOST, 0))
            .await
            .expect("websocket backend binds");
        let backend_port = backend.local_addr().expect("backend address").port();
        let backend_task = tokio::spawn(async move {
            let (mut stream, _) = backend.accept().await.expect("backend accepts");
            let mut request = Vec::new();
            let mut byte = [0_u8; 1];
            while !request.ends_with(b"\r\n\r\n") {
                stream.read_exact(&mut byte).await.expect("reads handshake");
                request.push(byte[0]);
            }
            stream
                .write_all(
                    b"HTTP/1.1 101 Switching Protocols\r\nConnection: Upgrade\r\nUpgrade: \
                      websocket\r\nSec-WebSocket-Accept: test\r\n\r\n",
                )
                .await
                .expect("writes upgrade");
            let mut payload = [0_u8; 4];
            stream
                .read_exact(&mut payload)
                .await
                .expect("reads payload");
            stream.write_all(&payload).await.expect("echoes payload");
        });

        let options = ProxyOptions::new(0, move || {
            vec![ProxyRoute::new("ws.localhost", backend_port)]
        });
        let (address, shutdown, proxy_task) = start_proxy(options).await;
        let mut stream = tokio::net::TcpStream::connect(address)
            .await
            .expect("connects to proxy");
        stream
            .write_all(
                b"GET /socket HTTP/1.1\r\nHost: ws.localhost\r\nConnection: Upgrade\r\nUpgrade: \
                  websocket\r\nSec-WebSocket-Key: dGVzdA==\r\nSec-WebSocket-Version: 13\r\n\r\n",
            )
            .await
            .expect("writes handshake");
        let mut response = Vec::new();
        let mut byte = [0_u8; 1];
        while !response.ends_with(b"\r\n\r\n") {
            stream.read_exact(&mut byte).await.expect("reads handshake");
            response.push(byte[0]);
        }
        assert!(String::from_utf8_lossy(&response).starts_with("HTTP/1.1 101"));
        stream.write_all(b"ping").await.expect("writes payload");
        let mut echoed = [0_u8; 4];
        stream.read_exact(&mut echoed).await.expect("reads echo");
        assert_eq!(&echoed, b"ping");

        shutdown.shutdown();
        proxy_task.await.expect("proxy joins");
        backend_task.await.expect("backend joins");
    }

    #[tokio::test]
    async fn tls_http1_fallback_relays_websocket_upgrade() {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};

        let backend = TcpListener::bind((Ipv4Addr::LOCALHOST, 0))
            .await
            .expect("websocket backend binds");
        let backend_port = backend.local_addr().expect("backend address").port();
        let backend_task = tokio::spawn(async move {
            let (mut stream, _) = backend.accept().await.expect("backend accepts");
            let mut request = Vec::new();
            let mut byte = [0_u8; 1];
            while !request.ends_with(b"\r\n\r\n") {
                stream.read_exact(&mut byte).await.expect("reads handshake");
                request.push(byte[0]);
            }
            stream
                .write_all(
                    b"HTTP/1.1 101 Switching Protocols\r\nConnection: Upgrade\r\nUpgrade: \
                      websocket\r\nSec-WebSocket-Accept: test\r\n\r\n",
                )
                .await
                .expect("writes upgrade");
            let mut payload = [0_u8; 4];
            stream
                .read_exact(&mut payload)
                .await
                .expect("reads payload");
            stream.write_all(&payload).await.expect("echoes payload");
        });

        let (state_dir, tls, roots) = tls_fixture();
        let mut options = ProxyOptions::new(0, move || {
            vec![ProxyRoute::new("socket.app.localhost", backend_port)]
        });
        options.bind_address = Some(IpAddr::V4(Ipv4Addr::LOCALHOST));
        options.tls = Some(tls);
        options.sni_state_dir = Some(state_dir.path().to_path_buf());
        options.http_redirect_port = None;
        let server = ProxyServer::bind(options).await.expect("TLS proxy binds");
        let address = server.local_addr().expect("proxy address");
        let shutdown = server.shutdown_handle();
        let proxy_task = tokio::spawn(async move {
            server.run().await.expect("proxy runs");
        });

        let tcp = tokio::net::TcpStream::connect(address)
            .await
            .expect("connects to TLS proxy");
        let server_name =
            ServerName::try_from("socket.app.localhost").expect("valid exact server name");
        let mut stream = tls_connector(roots, b"http/1.1")
            .connect(server_name, tcp)
            .await
            .expect("negotiates HTTP/1.1 TLS");
        assert_eq!(
            stream.get_ref().1.alpn_protocol(),
            Some(b"http/1.1".as_slice())
        );
        stream
            .write_all(
                b"GET /socket HTTP/1.1\r\nHost: socket.app.localhost\r\nConnection: \
                  Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Key: \
                  dGVzdA==\r\nSec-WebSocket-Version: 13\r\n\r\n",
            )
            .await
            .expect("writes handshake");
        let mut response = Vec::new();
        let mut byte = [0_u8; 1];
        while !response.ends_with(b"\r\n\r\n") {
            stream.read_exact(&mut byte).await.expect("reads handshake");
            response.push(byte[0]);
        }
        assert!(String::from_utf8_lossy(&response).starts_with("HTTP/1.1 101"));
        stream.write_all(b"ping").await.expect("writes payload");
        let mut echoed = [0_u8; 4];
        stream.read_exact(&mut echoed).await.expect("reads echo");
        assert_eq!(&echoed, b"ping");

        shutdown.shutdown();
        proxy_task.await.expect("proxy joins");
        backend_task.await.expect("backend joins");
    }
}
