[package]
name = "turborepo-signals"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
futures = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full", "time"] }

[dev-dependencies]

[lints]
workspace = true
