// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteCache } from "./RemoteCache";

/**
 * Global configuration that applies to all tasks in the monorepo.
 *
 * When `futureFlags.globalConfiguration` is enabled, these fields live
 * under the top-level `"global"` key instead of being scattered across
 * the root of turbo.json.
 *
 * When adding a new field, also update:
 * 1. The corresponding top-level field on `RawTurboJson`
 * 2. `resolve_global_config()` on `RawTurboJson`
 * 3. `validate_no_top_level_global_keys()` in this file
 * 4. `WithMetadata` impl in `parser.rs`
 * 5. `GlobalConfig` in `config-v2.ts` and `generate_global_config_interface()`
 *    in schema-gen
 */
export type GlobalConfig = { 
/**
 * A list of globs for files that implicitly affect all tasks.
 *
 * These files are prepended to every task's `inputs` during engine
 * construction rather than being folded into the global hash. This
 * allows individual tasks to exclude specific global files via
 * negation globs.
 */
inputs?: Array<string>, 
/**
 * A list of environment variables for implicit global hash dependencies.
 *
 * Unlike `inputs` (which become per-task inputs), these variables are
 * included in the global hash and affect all task hashes uniformly.
 */
env?: Array<string>, 
/**
 * An allowlist of environment variables that should be made to all tasks,
 * but should not contribute to the task's cache key.
 */
passThroughEnv?: Array<string>, 
/**
 * Enable use of the UI for `turbo`.
 */
ui?: UI, 
/**
 * Disable check for `packageManager` in root `package.json`.
 */
dangerouslyDisablePackageManagerCheck?: boolean, 
/**
 * Deprecated: The daemon is no longer used for `turbo run`.
 */
daemon?: boolean, 
/**
 * Turborepo's Environment Modes allow you to control which environment
 * variables are available to a task at runtime.
 */
envMode?: EnvMode, 
/**
 * Specify the filesystem cache directory.
 */
cacheDir?: string, 
/**
 * When set to `true`, disables the update notification that appears when
 * a new version of `turbo` is available.
 */
noUpdateNotifier?: boolean, 
/**
 * Set/limit the maximum concurrency for task execution.
 */
concurrency?: string, 
/**
 * Configuration options when interfacing with the remote cache.
 */
remoteCache?: RemoteCache, 
/**
 * Maximum age of local cache entries before automatic eviction.
 *
 * Accepts a human-readable duration string (e.g. `"7d"`, `"24h"`,
 * `"2w"`). Set to `"0"` to disable eviction (the default).
 * Entries older than this value are removed at the start of each run.
 */
cacheMaxAge?: string, 
/**
 * Maximum total size of the local filesystem cache.
 *
 * Accepts a human-readable size string (e.g. `"10GB"`, `"500MB"`).
 * When exceeded, the oldest entries are evicted until the cache is
 * under the limit. Set to `"0"` to disable (the default).
 */
cacheMaxSize?: string, };
