// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single incremental cache partition.
 *
 * Each partition represents a distinct set of tool-managed incremental
 * artifacts (e.g. `.tsbuildinfo`, Rust `target/debug/incremental/`) that
 * turbo will persist across runs via remote cache to speed up cache misses.
 */
export type IncrementalPartition = { 
/**
 * Glob patterns of incremental artifact files to cache. Paths are
 * relative to the package directory. Supports exclusion patterns.
 */
outputs?: Array<string>, 
/**
 * Glob patterns of files that invalidate this partition's incremental
 * cache. When omitted, the partition key does not include an input hash.
 */
inputs?: Array<string>, };
