// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for a pipeline task.
 *
 * The name of a task that can be executed by turbo. If turbo finds a
 * workspace package with a `package.json` scripts object with a matching
 * key, it will apply the pipeline task configuration to that npm script
 * during execution.
 */
export type Pipeline = {
  /**
   * A human-readable description of what this task does.
   *
   * This field is for documentation purposes only and does not affect
   * task execution or caching behavior.
   */
  description: string | null;
  /**
   * Whether or not to cache the outputs of the task.
   *
   * Setting cache to false is useful for long-running "watch" or
   * development mode tasks.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#cache
   */
  cache: boolean | null;
  /**
   * The list of tasks that this task depends on.
   *
   * Prefixing an item in `dependsOn` with a `^` prefix tells turbo that
   * this task depends on the package's topological dependencies completing
   * the task first. Items without a `^` prefix express the relationships
   * between tasks within the same package.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#dependson
   */
  dependsOn: Array<string> | null;
  /**
   * A list of environment variables that this task depends on.
   *
   * Note: If you are migrating from a turbo version 1.5 or below, you may
   * be used to prefixing your variables with a `$`. You no longer need to
   * use the `$` prefix.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#env
   */
  env: Array<string> | null;
  /**
   * The set of glob patterns to consider as inputs to this task.
   *
   * Changes to files covered by these globs will cause a cache miss and
   * the task will be rerun. If a file has been changed that is **not**
   * included in the set of globs, it will not cause a cache miss.
   * If omitted or empty, all files in the package are considered as inputs.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#inputs
   */
  inputs: Array<string> | null;
  /**
   * An allowlist of environment variables that should be made available
   * in this task's environment, but should not contribute to the task's
   * cache key, e.g. `AWS_SECRET_KEY`.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#passthroughenv
   */
  passThroughEnv: Array<string> | null;
  /**
   * Indicates whether the task exits or not.
   *
   * Setting `persistent` to `true` tells turbo that this is a long-running
   * task and will ensure that other tasks cannot depend on it.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#persistent
   */
  persistent: boolean | null;
  /**
   * Label a persistent task as interruptible to allow it to be restarted
   * by `turbo watch`.
   *
   * `turbo watch` watches for changes to your packages and automatically
   * restarts tasks that are affected. However, if a task is persistent,
   * it will not be restarted by default. To enable restarting persistent
   * tasks, set `interruptible` to `true`.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#interruptible
   */
  interruptible: boolean | null;
  /**
   * The set of glob patterns indicating a task's cacheable filesystem
   * outputs.
   *
   * Turborepo captures task logs for all tasks. This enables us to cache
   * tasks whose runs produce no artifacts other than logs (such as linters).
   * Logs are always treated as a cacheable artifact and never need to be
   * specified.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#outputs
   */
  outputs: Array<string> | null;
  /**
   * Output mode for the task.
   *
   * Documentation: https://turborepo.dev/docs/reference/run#--output-logs-option
   */
  outputLogs: OutputLogs | null;
  /**
   * Mark a task as interactive allowing it to receive input from stdin.
   *
   * Interactive tasks must be marked with `"cache": false` as the input
   * they receive from stdin can change the outcome of the task.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#interactive
   */
  interactive: boolean | null;
  /**
   * A list of tasks that will run alongside this task.
   *
   * Tasks in this list will not be run until completion before this task
   * starts execution.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#with
   */
  with: Array<string> | null;
};
