// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteCache } from "./RemoteCache";

/**
 * Configuration schema for turbo.json.
 *
 * An object representing the task dependency graph of your project.
 * turbo interprets these conventions to schedule, execute, and cache
 * the outputs of tasks in your project.
 *
 * Documentation: https://turborepo.dev/docs/reference/configuration
 */
export type RawTurboJson = {
  /**
   * JSON Schema URL for validation.
   */
  $schema: string | null;
  /**
   * This key is only available in Workspace Configs and cannot be used in
   * your root turbo.json.
   *
   * Tells turbo to extend your root `turbo.json` and overrides with the
   * keys provided in your Workspace Configs. Currently, only the `["//"]`
   * value is allowed.
   */
  extends: Array<string> | null;
  /**
   * A list of globs to include in the set of implicit global hash
   * dependencies.
   *
   * The contents of these files will be included in the global hashing
   * algorithm and affect the hashes of all tasks.
   *
   * This is useful for busting the cache based on:
   * - `.env` files (not in Git)
   * - Any root level file that impacts package tasks that are not
   *   represented in the traditional dependency graph (e.g. a root
   *   `tsconfig.json`, `jest.config.ts`, `.eslintrc`, etc.)
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#globaldependencies
   */
  globalDependencies: Array<string> | null;
  /**
   * A list of environment variables for implicit global hash dependencies.
   *
   * The variables included in this list will affect all task hashes.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#globalenv
   */
  globalEnv: Array<string> | null;
  /**
   * An allowlist of environment variables that should be made to all tasks,
   * but should not contribute to the task's cache key, e.g.
   * `AWS_SECRET_KEY`.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#globalpassthroughenv
   */
  globalPassThroughEnv: Array<string> | null;
  /**
   * An object representing the task dependency graph of your project.
   *
   * turbo interprets these conventions to schedule, execute, and cache the
   * outputs of tasks in your project.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#tasks
   */
  tasks: null;
  /**
   * Configuration options when interfacing with the remote cache.
   *
   * Documentation: https://turborepo.dev/docs/core-concepts/remote-caching
   */
  remoteCache: RemoteCache | null;
  /**
   * Enable use of the UI for `turbo`.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#ui
   */
  ui: UI | null;
  /**
   * Disable check for `packageManager` in root `package.json`.
   *
   * This is highly discouraged as it leaves `turbo` dependent on system
   * configuration to infer the correct package manager. Some turbo features
   * are disabled if this is set to true.
   */
  dangerouslyDisablePackageManagerCheck: boolean | null;
  /**
   * Turborepo runs a background process to pre-calculate some expensive
   * operations. This standalone process (daemon) is a performance
   * optimization, and not required for proper functioning of `turbo`.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#daemon
   */
  daemon: boolean | null;
  /**
   * Turborepo's Environment Modes allow you to control which environment
   * variables are available to a task at runtime.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#envmode
   */
  envMode: EnvMode | null;
  /**
   * Specify the filesystem cache directory.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#cachedir
   */
  cacheDir: string | null;
  /**
   * When set to `true`, disables the update notification that appears when
   * a new version of `turbo` is available.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#noupdatenotifier
   */
  noUpdateNotifier: boolean | null;
  /**
   * Used to tag a package for boundaries rules.
   *
   * Boundaries rules can restrict which packages a tag group can import
   * or be imported by.
   */
  tags: Array<string> | null;
  /**
   * Configuration for `turbo boundaries`.
   *
   * Allows users to restrict a package's dependencies and dependents.
   */
  boundaries: BoundariesConfig | null;
  /**
   * Set/limit the maximum concurrency for task execution.
   *
   * Must be an integer greater than or equal to `1` or a percentage value
   * like `50%`. Use `1` to force serial execution (one task at a time).
   * Use `100%` to use all available logical processors.
   *
   * Documentation: https://turborepo.dev/docs/reference/configuration#concurrency
   */
  concurrency: string | null;
  /**
   * Opt into breaking changes prior to major releases, experimental
   * features, and beta features.
   */
  futureFlags: FutureFlags | null;
};
