// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration options that control how turbo interfaces with the remote
 * cache.
 *
 * Documentation: https://turborepo.dev/docs/core-concepts/remote-caching
 */
export type RemoteCache = {
  /**
   * Set endpoint for API calls to the remote cache.
   *
   * Documentation: https://turborepo.dev/docs/core-concepts/remote-caching#self-hosting
   */
  apiUrl: string | null;
  /**
   * Set endpoint for requesting tokens during `turbo login`.
   *
   * Documentation: https://turborepo.dev/docs/core-concepts/remote-caching#self-hosting
   */
  loginUrl: string | null;
  /**
   * The slug of the Remote Cache team.
   *
   * Value will be passed as `slug` in the querystring for all Remote
   * Cache HTTP calls.
   */
  teamSlug: string | null;
  /**
   * The ID of the Remote Cache team.
   *
   * Value will be passed as `teamId` in the querystring for all Remote
   * Cache HTTP calls. Must start with `team_` or it will not be used.
   */
  teamId: string | null;
  /**
   * Indicates if signature verification is enabled for requests to the
   * remote cache.
   *
   * When `true`, Turborepo will sign every uploaded artifact using the
   * value of the environment variable `TURBO_REMOTE_CACHE_SIGNATURE_KEY`.
   * Turborepo will reject any downloaded artifacts that have an invalid
   * signature or are missing a signature.
   */
  signature: boolean | null;
  /**
   * When enabled, any HTTP request will be preceded by an OPTIONS request
   * to determine if the request is supported by the endpoint.
   *
   * Documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests
   */
  preflight: boolean | null;
  /**
   * Sets a timeout for remote cache operations.
   *
   * Value is given in seconds and only whole values are accepted.
   * If `0` is passed, then there is no timeout for any cache operations.
   */
  timeout: number | null;
  /**
   * Indicates if the remote cache is enabled.
   *
   * When `false`, Turborepo will disable all remote cache operations,
   * even if the repo has a valid token. If `true`, remote caching is
   * enabled, but still requires the user to login and link their repo
   * to a remote cache.
   *
   * Documentation: https://turborepo.dev/docs/core-concepts/remote-caching
   */
  enabled: boolean | null;
  /**
   * Sets a timeout for remote cache uploads.
   *
   * Value is given in seconds and only whole values are accepted.
   * If `0` is passed, then there is no timeout for any remote cache uploads.
   */
  uploadTimeout: number | null;
};
