// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StructuredInput = { mode?: string, globs?: Array<string>, withDefaults?: boolean, from?: Array<string>, };
