[package]
name = "turborepo-cli-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
turborepo-lib = { path = "../crates/turborepo-lib", default-features = false, features = ["rustls-tls", "cli-fuzz"] }

[[bin]]
name = "cli_parser"
path = "fuzz_targets/cli_parser.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
