[package]
name = "turborepo-run-opts"
version = "0.1.0"
edition.workspace = true
license = "MIT"
description = "Resolved options for Turborepo runs"

[lints]
workspace = true

[dependencies]
camino = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }

turbopath = { workspace = true }
turborepo-api-client = { workspace = true }
turborepo-cache = { workspace = true }
turborepo-ci = { workspace = true }
turborepo-config = { workspace = true }
turborepo-task-executor = { workspace = true }
turborepo-task-graph = { workspace = true }
turborepo-turbo-json = { workspace = true }
turborepo-types = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
insta = { workspace = true }
serde_json = { workspace = true }
temp-env = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
turborepo-task-id = { workspace = true }
