packages:
  - "apps/*"
  - "packages/*"
autoInstallPeers: true
minimumReleaseAgeExclude:
  - '@rslint/core@0.8.0'
  - '@rslint/native-darwin-arm64@0.8.0'
  - '@rslint/native-darwin-x64@0.8.0'
  - '@rslint/native-linux-arm64-gnu@0.8.0'
  - '@rslint/native-linux-arm64-musl@0.8.0'
  - '@rslint/native-linux-x64-gnu@0.8.0'
  - '@rslint/native-linux-x64-musl@0.8.0'
  - '@rslint/native-win32-arm64-msvc@0.8.0'
  - '@rslint/native-win32-x64-msvc@0.8.0'
