// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for `turbo boundaries`.
 *
 * Allows users to restrict a package's dependencies and dependents.
 */
export type BoundariesConfig = {
  /**
   * The boundaries rules for tags.
   *
   * Restricts which packages can import a tag and which packages a tag can
   * import.
   */
  tags: { [key in string]?: TagRules } | null;
  /**
   * Declares any implicit dependencies, i.e. any dependency not declared in
   * a `package.json`.
   *
   * These can include dependencies automatically injected by a framework or
   * a testing library.
   */
  implicitDependencies: Array<string> | null;
  /**
   * Rules for a package's dependencies.
   *
   * Restricts which packages this package can import.
   */
  dependencies: Permissions | null;
  /**
   * Rules for a package's dependents.
   *
   * Restricts which packages can import this package.
   */
  dependents: Permissions | null;
};
