// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission rules for boundaries.
 */
export type Permissions = {
  /**
   * Lists which tags are allowed.
   *
   * Any tag not included will be banned. If omitted, all tags are permitted.
   */
  allow: Array<string> | null;
  /**
   * Lists which tags are banned.
   */
  deny: Array<string> | null;
};
