// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Boundary rules for a tag.
 *
 * Restricts which packages a tag can import and which packages can import this
 * tag.
 */
export type TagRules = {
  /**
   * Rules for a tag's dependencies.
   *
   * Restricts which packages a tag can import.
   */
  dependencies: Permissions | null;
  /**
   * Rules for a tag's dependents.
   *
   * Restricts which packages can import this tag.
   */
  dependents: Permissions | null;
};
