export const users = [
  {
    caption: "Vercel",
    image: "/images/logos/vercel.svg",
    infoLink: "https://vercel.com",
    pinned: true,
  },
  {
    caption: "AWS",
    image: "/images/logos/aws.svg",
    infoLink: "https://aws.amazon.com",
    pinned: true,
  },
  {
    caption: "Netflix",
    image: "/images/logos/netflix.svg",
    infoLink: "https://netflix.com",
    pinned: true,
  },
  {
    caption: "Microsoft",
    image: "/images/logos/microsoft.svg",
    infoLink: "https://microsoft.com",
    pinned: true,
  },
  {
    caption: "Disney",
    image: "/images/logos/disney.svg",
    infoLink: "https://disney.com",
    pinned: true,
  },
  {
    caption: "PayPal",
    image: "/images/logos/paypal.svg",
    infoLink: "https://paypal.com",
    pinned: true,
  },
  {
    caption: "Adobe",
    image: "/images/logos/adobe.svg",
    infoLink: "https://adobe.com",
    pinned: true,
  },
  {
    caption: "Shopify",
    image: "/images/logos/shopify.svg",
    infoLink: "https://shopify.com",
    pinned: true,
  },
  {
    caption: "SAP",
    image: "/images/logos/sap.svg",
    infoLink: "https://sap.com",
    pinned: true,
  },
  {
    caption: "Citadel",
    image: "/images/logos/citadel.svg",
    infoLink: "https://citadel.com",
    pinned: true,
  },
  {
    caption: "Twilio",
    image: "/images/logos/twilio.svg",
    infoLink: "https://twilio.com",
    pinned: true,
  },
  {
    caption: "Line",
    image: "/images/logos/line.svg",
    infoLink: "https://line.me",
    pinned: true,
  },
  {
    caption: "Volvo",
    image: "/images/logos/volvo.svg",
    infoLink: "https://volvo.com",
    pinned: true,
  },
  {
    caption: "Hearst",
    image: "/images/logos/hearst.svg",
    infoLink: "https://hearst.com",
    pinned: true,
  },
  {
    caption: "The Washington Post",
    image: "/images/logos/washingtonpost.svg",
    infoLink: "https://washingtonpost.com",
    pinned: true,
  },
  {
    caption: "Wayfair",
    image: "/images/logos/wayfair.svg",
    infoLink: "https://wayfair.com",
    pinned: true,
  },
  {
    caption: "Hulu",
    image: "/images/logos/hulu.svg",
    infoLink: "https://hulu.com",
    pinned: true,
  },
  {
    caption: "CrowdStrike",
    image: "/images/logos/crowdstrike.svg",
    infoLink: "https://crowdstrike.com",
    pinned: true,
  },
  {
    caption: "Binance",
    image: "/images/logos/binance.svg",
    infoLink: "https://binance.com",
    pinned: true,
  },
  {
    caption: "Plex",
    image: "/images/logos/plex.svg",
    infoLink: "https://plex.com",
    pinned: true,
  },
  {
    caption: "Groupon",
    image: "/images/logos/groupon.svg",
    infoLink: "https://groupon.com",
    pinned: true,
  },
  {
    caption: "GoodRx",
    image: "/images/logos/goodrx.svg",
    infoLink: "https://goodrx.com",
    pinned: true,
  },
];
