[package]
name = "turborepo-prune"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"
description = "Language-agnostic pruned monorepo orchestration for Turborepo"

[lints]
workspace = true

[dependencies]
globwalk = { version = "0.1.0", path = "../turborepo-globwalk" }
miette = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
turbopath = { workspace = true }
turborepo-config = { path = "../turborepo-config" }
turborepo-engine = { workspace = true }
turborepo-fs = { workspace = true }
turborepo-lockfiles = { workspace = true }
turborepo-microfrontends-config = { workspace = true }
turborepo-package-watcher = { workspace = true }
turborepo-repository = { workspace = true }
turborepo-telemetry = { path = "../turborepo-telemetry" }
turborepo-turbo-json = { workspace = true }
turborepo-ui = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
turborepo-errors = { workspace = true }
