[package]
name = "turborepo-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
# Allows configuring a specific tls backend for reqwest.
# See top level Cargo.toml for more details.
default = ["rustls-tls"]
native-tls = [
  "turborepo-api-client/native-tls",
  "turbo-updater/native-tls",
  "turborepo-run/native-tls",
  "turborepo-watch/native-tls",
]
rustls-tls = [
  "turborepo-api-client/rustls-tls",
  "turbo-updater/rustls-tls",
  "turborepo-run/rustls-tls",
  "turborepo-watch/rustls-tls",
]
heap-dhat = ["dep:dhat"]
pprof = ["turborepo-tracing/pprof"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
assert_cmd = { workspace = true }
async-stream = "0.3.4"
biome_deserialize = { workspace = true }
biome_json_parser = { workspace = true }
insta = { workspace = true }
itertools = { workspace = true }
port_scanner = { workspace = true }
pretty_assertions = { workspace = true }
serial_test = "3.0"
temp-env = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }
tracing.workspace = true
turborepo-repository = { path = "../turborepo-repository", features = [
  "test-util",
] }
turborepo-vercel-api-mock = { workspace = true }

[lints]
workspace = true

[dependencies]
camino = "1.1.4"
console = { workspace = true }
dhat = { workspace = true, optional = true }
dialoguer = { workspace = true, features = ["fuzzy-select", "password"] }
dirs-next = "2.0.0"
either = { workspace = true }
futures = { workspace = true }
go-parse-duration = "0.1.1"
human-panic = "1.2.1"
humantime = "2.1.0"
ignore = "0.4.24"
indicatif = { workspace = true }
itertools = { workspace = true }
libc = "0.2.140"
merge = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
pidlock = { path = "../turborepo-pidlock" }
prost = "0.14"
rand = { workspace = true }
rayon = "1.7.0"
regex.workspace = true
reqwest = { workspace = true, default-features = false, features = ["json"] }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
sha2 = { workspace = true }
shared_child = "1.0.0"

sysinfo = "0.27.7"
thiserror = { workspace = true }
time = "0.3.20"
tiny-gradient = { workspace = true }
tokio = { workspace = true, features = ["full", "time"] }
tokio-stream = { version = "0.1.12", features = ["net"] }
tonic = { version = "0.14", features = ["transport"] }

tracing-appender = "0.2.2"
tracing.workspace = true
url = { workspace = true }
usage = { package = "usage-rs", version = "=6.5.0", features = ["completions"] }

turbo-updater = { workspace = true }
turbopath = { workspace = true }
turborepo-ai-agents = { workspace = true }
turborepo-api-client = { workspace = true }
turborepo-auth = { path = "../turborepo-auth" }
turborepo-boundaries = { workspace = true }
turborepo-ci = { workspace = true }
turborepo-config = { path = "../turborepo-config" }
turborepo-daemon = { workspace = true }
turborepo-devtools = { path = "../turborepo-devtools" }
turborepo-dirs = { path = "../turborepo-dirs" }
turborepo-engine = { workspace = true }
turborepo-fixed-map = { workspace = true }
turborepo-frameworks = { workspace = true }
turborepo-gitignore = { workspace = true }
turborepo-graph-utils = { path = "../turborepo-graph-utils" }
turborepo-json-rewrite = { path = "../turborepo-json-rewrite" }
turborepo-log = { workspace = true }
turborepo-microfrontends = { workspace = true }
turborepo-microfrontends-config = { workspace = true }
turborepo-otel = { workspace = true }
turborepo-package-watcher = { workspace = true }
turborepo-process = { workspace = true }
turborepo-profile-md = { workspace = true }
turborepo-prune = { workspace = true }
turborepo-query-api = { workspace = true }
turborepo-rayon-compat = { workspace = true }
turborepo-repository = { path = "../turborepo-repository" }
turborepo-run = { workspace = true, default-features = false }
turborepo-run-opts = { workspace = true }
turborepo-shim = { workspace = true }
turborepo-signals = { workspace = true }
turborepo-task-executor = { workspace = true }
turborepo-task-id = { workspace = true }
turborepo-telemetry = { path = "../turborepo-telemetry" }
turborepo-tracing = { workspace = true }
turborepo-turbo-json = { path = "../turborepo-turbo-json" }
turborepo-types = { workspace = true }
turborepo-ui = { workspace = true, features = ["tui"] }
turborepo-unescape = { workspace = true }
turborepo-vercel-api = { path = "../turborepo-vercel-api" }
turborepo-watch = { workspace = true }
unrs_resolver = { workspace = true }
webbrowser = { workspace = true }
which = { workspace = true }


[target.'cfg(target_os = "windows")'.dependencies]
async-io = "2"
