ARG BASE_IMG
FROM ${BASE_IMG}

RUN apt-get update && apt-get install -y protobuf-compiler

RUN 

# Get Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
