packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  pnpm: true
  unrs-resolver: true
  workerd: true

supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current
