[package]
name = "turbo-updater"
version = "0.1.0"
edition = "2021"
description = "Minimal wrapper around update-informer to provide npm registry support and consistent UI"
license = "MIT"
publish = false

[features]
# Allows configuring a specific tls backend for reqwest.
# See top level Cargo.toml for more details.
native-tls = ["reqwest/native-tls", "update-informer/native-tls"]
rustls-tls = ["reqwest/rustls-tls", "update-informer/rustls-tls"]

[lints]
workspace = true

[dependencies]
atty = { workspace = true }
console = { workspace = true }
reqwest = { workspace = true, features = ["json", "blocking"] }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
update-informer = { version = "1.1", default-features = false, features = [
  "reqwest",
] }
