packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true

catalogs:
  sveltejs:
    "@sveltejs/adapter-auto": "^7.0.1"
    "@sveltejs/kit": "^2.69.2"
    "@sveltejs/package": "^2.5.8"
    "@sveltejs/vite-plugin-svelte": "^7.2.0"
    "eslint-plugin-svelte": "^3.20.0"
    "prettier-plugin-svelte": "^4.1.1"
    "svelte": "^5.56.4"
    "svelte-check": "^4.7.2"
    "svelte-eslint-parser": "^1.8.0"
