[package]
name = "globwalk"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
camino = { workspace = true }
itertools.workspace = true
path-clean = "1.0.1"
path-slash = "0.2.1"
rayon = "1"
regex.workspace = true
thiserror.workspace = true
tracing = "0.1.37"
turbopath.workspace = true
walkdir = "2.3.3"
wax.workspace = true

[dev-dependencies]
tempfile = { workspace = true }
test-case = "3.1.0"
