<script setup lang="ts">
import { Page } from "ui";
import { name } from "./package.json";

useHead({
  title: "Create Turborepo (vue-nuxt:docs)",
  meta: [{ name: "description", content: "Generated by create turbo" }],
});
</script>

<template>
  <Page :app-name="name" />
</template>
