/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * A single external package resolved from the workspace lockfile, as a fully
 * qualified `name` and `version` (e.g. `{ name: "lodash", version: "4.17.21"
 * }`). Peer-dependency closures are stripped so `${name}@${version}` is
 * always a plain `pkg@1.2.3` identifier.
 */
export interface LockfilePackage {
  name: string;
  version: string;
}
/**
 * The external packages referenced by a workspace's lockfile, plus any
 * reasons the lockfile could not be fully parsed. Intended to be consumed for
 * metrics: a non-empty `errors` list (or an empty `packages` list alongside
 * one) signals that extraction was incomplete.
 */
export interface LockfilePackages {
  /**
   * Fully qualified external packages found in the lockfile, sorted and
   * deduplicated.
   */
  packages: Array<LockfilePackage>;
  /**
   * Human-readable reasons the lockfile could not be read or fully parsed.
   * Empty when extraction succeeded.
   */
  errors: Array<string>;
}
export class Package {
  name: string;
  /** The absolute path to the package root. */
  readonly absolutePath: string;
  /** The relative path from the workspace root to the package root. */
  readonly relativePath: string;
}
/**
 * Wrapper for dependents and dependencies.
 * Each are a list of package paths, relative to the workspace root.
 */
export class PackageDetails {
  /** the package's dependencies */
  readonly dependencies: Array<string>;
  /** the packages that depend on this package */
  readonly dependents: Array<string>;
}
export class PackageManager {
  /** The package manager name in lower case. */
  readonly name: string;
  /**
   * The declared package manager version (from the root `package.json`
   * `packageManager` or `devEngines.packageManager` field), if available.
   */
  readonly version?: string;
}
export class Workspace {
  /** The absolute path to the workspace root. */
  readonly absolutePath: string;
  /** `true` when the workspace is a multi-package workspace. */
  readonly isMultiPackage: boolean;
  /** The package manager used by the workspace. */
  readonly packageManager: PackageManager;
  /**
   * Finds the workspace root from the given path, and returns a new
   * Workspace.
   */
  static find(path?: string | undefined | null): Promise<Workspace>;
  /** Finds and returns packages within the workspace. */
  findPackages(): Promise<Array<Package>>;
  /**
   * Returns a map of packages within the workspace, its dependencies and
   * dependents. The response looks like this:
   *  {
   *    "package-path": {
   *      "dependents": ["dependent1_path", "dependent2_path"],
   *      "dependencies": ["dependency1_path", "dependency2_path"]
   *      }
   *  }
   */
  findPackagesWithGraph(): Promise<Record<string, PackageDetails>>;
  /**
   * Returns all external packages from the JavaScript resolution domain as
   * `npm/<name>@<version>` strings. Cargo identities are excluded to
   * preserve the historical lockfile-only listing.
   */
  packagesFromLockfile(): Promise<Array<string>>;
  /**
   * Returns the external packages referenced by the workspace lockfile as a
   * flat, sorted, deduplicated list of `{ name, version }` structs, together
   * with any reasons the lockfile could not be fully parsed.
   *
   * Unlike [`Self::packages_from_lockfile`], this never rejects: a missing
   * or unparseable lockfile yields an empty `packages` list and a populated
   * `errors` list rather than an exception, so callers can emit metrics on
   * both success and failure. Package manager identity is exposed separately
   * on [`Workspace::package_manager`].
   */
  lockfilePackages(): Promise<LockfilePackages>;
  /**
   * Given a set of "changed" files, returns a set of packages that are
   * "affected" by the changes. The `files` argument is expected to be a list
   * of strings relative to the monorepo root and use the current system's
   * path separator.
   */
  affectedPackages(
    files: Array<string>,
    base?: string | undefined | null,
    optimizeGlobalInvalidations?: boolean | undefined | null
  ): Promise<Array<Package>>;
  /**
   * Given a path (relative to the workspace root), returns the
   * package that contains it.
   *
   * This is a naive implementation that simply "iterates-up". If this
   * function is expected to be called many times for files that are deep
   * within the same package, we could optimize this by caching the
   * containing-package of every ancestor.
   */
  findPackageByPath(path: string): Promise<Package>;
}
