/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Workspace {
  readonly absolutePath: string;
  readonly isMultiPackage: boolean;
  static find(path?: string | undefined | null): Promise<Workspace>;
  packageManager(): PackageManager;
  findPackages(): Promise<Array<Package>>;
}
export class PackageManager {
  readonly name: string;
}
export class Package {
  readonly absolutePath: string;
}
