name: Example tests
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - examples/kitchen-sink/**
      - turborepo-tests/example-kitchen-sink-*/**
      - turborepo-tests/helpers/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  kitchen-sink:
    name: "kitchen-sink"
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Disable corepack. actions/setup-node invokes other package managers and
      # that causes corepack to throw an error, so we disable it first.
      - name: Disable corepack
        shell: bash
        run: corepack disable

      - name: Setup Turborepo Environment
        uses: ./.github/actions/setup-turborepo-environment
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          node-version: "22"

      - name: Install Global Turbo
        uses: ./.github/actions/install-global-turbo

      - name: Check kitchen-sink example
        shell: bash
        run: turbo run test --filter="@turborepo-examples-tests/kitchen-sink-*" --continue --token=${{ secrets.TURBO_TOKEN }} --team=${{ vars.TURBO_TEAM }} --env-mode=strict
