name: Examples tests
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  basic-example:
    name: "`basic`"
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for file changes
        id: changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^examples/basic/"; then
            echo "yes in examples/basic"
            echo "frontend=true" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^examples/kitchen-sink/"; then
            echo "yes in examples/kitchen-sink"
            echo "backend=true" >> $GITHUB_OUTPUT
          fi

      # Disable corepack. actions/setup-node invokes other package managers and
      # that causes corepack to throw an error, so we disable it first.
      - name: Disable corepack
        shell: bash
        run: corepack disable

      - name: Setup Turborepo Environment
        uses: ./.github/actions/setup-turborepo-environment
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          node-version: "22"

      - name: Install Global Turbo
        uses: ./.github/actions/install-global-turbo

      - name: Check examples
        if: ${{ contains(github.event.pull_request.files.*.path, 'examples/basic/') }}
        shell: bash
        run: turbo run test --filter="@turborepo-examples-tests/basic-*" --continue --token=${{ secrets.TURBO_TOKEN }} --team=${{ vars.TURBO_TEAM }} --env-mode=strict --concurrency=1

  kitchen-sink:
    name: "`kitchen-sink` example tests"
    timeout-minutes: 40
    if: ${{ contains(github.event.pull_request.files.*.path, 'examples/kitchen-sink/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Disable corepack. actions/setup-node invokes other package managers and
      # that causes corepack to throw an error, so we disable it first.
      - name: Disable corepack
        shell: bash
        run: corepack disable

      - name: Setup Turborepo Environment
        uses: ./.github/actions/setup-turborepo-environment
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          node-version: "22"

      - name: Install Global Turbo
        uses: ./.github/actions/install-global-turbo

      - name: Check examples
        if: ${{ contains(github.event.pull_request.files.*.path, 'examples/kitchen-sink/') }}
        shell: bash
        run: turbo run test --filter="@turborepo-examples-tests/kitchen-sink-*" --continue --token=${{ secrets.TURBO_TOKEN }} --team=${{ vars.TURBO_TEAM }} --env-mode=strict --concurrency=1
