name: Example tests - kitchen-sink
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - examples/kitchen-sink/**
      - turborepo-tests/example-kitchen-sink-*/**
      - turborepo-tests/helpers/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  kitchen-sink:
    name: kitchen-sink
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Run `kitchen-sink` example tests"
        uses: ./.github/actions/examples-tests
        with:
          node-version: "22"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          turbo-token: "${{ secrets.TURBO_TOKEN }}"
          turbo-team: "${{ vars.TURBO_TEAM }}"
          test-filter: "@turborepo-examples-tests/kitchen-sink-*"
