name: Example tests - with-svelte
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - examples/with-svelte/**
      - turborepo-tests/example-with-svelte-*/**
      - turborepo-tests/helpers/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  with-svelte-example:
    name: with-svelte
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Run `with-svelte` example tests"
        uses: ./.github/actions/examples-tests
        with:
          node-version: "22"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          turbo-token: "${{ secrets.TURBO_TOKEN }}"
          turbo-team: "${{ vars.TURBO_TEAM }}"
          test-filter: "@turborepo-examples-tests/with-svelte-*"
