name: JS Package Tests

on:
  workflow_call:

env:
  TURBO_TELEMETRY_MESSAGE_DISABLED: "1"

permissions:
  contents: read

jobs:
  js_packages:
    name: "(${{matrix.os.name}}, Node ${{matrix.node-version}})"
    timeout-minutes: 15
    runs-on: ${{ matrix.os.runner }}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu
            runner: ubuntu-latest
          - name: macos
            runner: macos-latest
        node-version:
          - 22
          - 24
          - 26
    env:
      TURBO_CACHE: ${{ github.event.pull_request.head.repo.full_name == github.repository && 'remote:rw' || 'local:rw' }}

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Turborepo Remote Cache
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: vercel/setup-turborepo-remote-cache-action@49d7b1b46ba4c9251e1977986bfe18336feabc8f # v1.1.0
        with:
          team: ${{ vars.TURBO_TEAM }}

      - name: "Setup Node"
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: Install Global Turbo
        uses: ./.github/actions/install-global-turbo

      - name: Run tests
        # We manually set TURBO_API to an empty string to override Hetzner env
        # @turbo/repository has its own native build matrix in the Test workflow.
        run: |
          TURBO_API= turbo run check-types test build package-checks --affected --filter="./packages/*" --filter="!@turbo/repository" --color --env-mode=strict
        env:
          NODE_VERSION: ${{ matrix.node-version }}
